### ISSUE TITLE
@PutMapping, @DeleteMapping

### ISSUE THREAD

**Issue by HGYEONG** [indongzz/daegu_dot_server#15]
PutMapping과 DeleteMapping을 사용하면 에러 405가 발생
위 API 대신 @RequestMapping으로 사용하여도 똑같은 에러가 발생
구글링해도 원인 알 수 없음... 해결책 없음...

대신 GetMapping과 PostMapping을 사용하면 해결 가능

**Comment by indongzz** [comment]
👍
